services:
  web:
    build: .
    image: dataviz
    ports:
      - '1334:1337'
    environment:
      - NODE_ENV=docker
    restart: always
    volumes:
      - ./data:/usr/app/Thalia/websites/dataviz/data

  db:
    image: postgres
    volumes:
      - dataviz_db:/var/lib/postgresql/data
    expose:
      - '5432'
    ports:
      - '5433:5432'
    environment:
      PGUSER: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'mysecretpassword'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready', '-d', 'postgres']
    restart: always

volumes:
  dataviz_db:
  data: