/**
 * Statues dataset source. Run: bun scripts/build-statues-csv.ts
 *
 * Inclusion rules (see docs/2026-08-09_statues.md):
 * - Women: prefer named non-royal public statues/busts (PSSA spirit). Allegory/royals
 *   only if tagged (e.g. Boudicca as woman + form=allegory_or_royal).
 * - Goats: freestanding, woman-with-goat, heraldic, architectural relief (curated).
 * - Every row needs lat/long + primary url. Approximate town pins: access=approx.
 */

export type StatueType =
  | 'woman'
  | 'woman_collective'
  | 'goat'
  | 'goat_with_figure'
  | 'goat_heraldic'
  | 'goat_relief'

export type StatueForm = 'statue' | 'bust' | 'group' | 'relief' | 'silhouette' | 'bench'

export type StatueAccess = 'public' | 'campus' | 'museum' | 'indoor' | 'rooftop' | 'approx'

export type StatueRow = {
  name: string
  type: StatueType
  location: string
  lat: number
  long: number
  artist: string
  owner: string
  source: string
  url: string
  year: string
  form: StatueForm
  access: StatueAccess
  notes: string
}

/** Existing + expanded catalogue. Coords from Wikipedia / Art UK / council pages where known; else town-level approx. */
export const statues: StatueRow[] = [
  // —— Existing core (normalised) ——
  { name: 'Millicent Fawcett', type: 'woman', location: 'Parliament Square, Westminster, London', lat: 51.5007, long: -0.1272, artist: 'Gillian Wearing', owner: 'GLA / Parliament Square', source: 'PSSA; Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Millicent_Fawcett', year: '2018', form: 'statue', access: 'public', notes: '' },
  { name: 'Emmeline Pankhurst (Rise up, Women)', type: 'woman', location: "St Peter's Square, Manchester", lat: 53.4781, long: -2.2434, artist: 'Hazel Reeves', owner: 'Manchester City Council', source: 'PSSA; Wikipedia', url: 'https://en.wikipedia.org/wiki/Rise_up,_Women', year: '2018', form: 'statue', access: 'public', notes: '' },
  { name: 'Mary Seacole', type: 'woman', location: "St Thomas' Hospital Gardens, London", lat: 51.5002, long: -0.1189, artist: 'Martin Jennings', owner: "Guy's and St Thomas' NHS", source: 'PSSA; Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Mary_Seacole', year: '2016', form: 'statue', access: 'public', notes: '' },
  { name: 'Mary Anning', type: 'woman', location: 'Gun Cliff Walk, Lyme Regis, Dorset', lat: 50.7256, long: -2.9348, artist: 'Denise Dutton', owner: 'Mary Anning Rocks', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2022', form: 'statue', access: 'public', notes: '' },
  { name: 'Jane Austen (Chawton)', type: 'woman', location: 'St Nicholas Church, Chawton, Hampshire', lat: 51.1333, long: -0.9833, artist: 'Adam Roud', owner: 'Local parish', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2018', form: 'statue', access: 'public', notes: '' },
  { name: 'Jane Austen (Basingstoke)', type: 'woman', location: 'Market Place, Basingstoke, Hampshire', lat: 51.2622, long: -1.0872, artist: 'Adam Roud', owner: 'Basingstoke', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2017', form: 'statue', access: 'public', notes: '' },
  { name: 'Jane Austen (Winchester)', type: 'woman', location: 'Cathedral Close, Winchester', lat: 51.0607, long: -1.3132, artist: 'Martin Jennings', owner: 'Winchester Cathedral', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2025', form: 'statue', access: 'public', notes: '' },
  { name: 'Nancy Astor', type: 'woman', location: 'Plymouth Hoe, Plymouth', lat: 50.3653, long: -4.1428, artist: 'Hayley Gibbs', owner: 'Plymouth City Council', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2019', form: 'statue', access: 'public', notes: '' },
  { name: 'Cilla Black', type: 'woman', location: 'Mathew Street, Liverpool', lat: 53.4056, long: -2.9883, artist: 'Andy Edwards / Emma Rodgers', owner: 'Liverpool', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2017', form: 'statue', access: 'public', notes: '' },
  { name: 'Floella Benjamin', type: 'woman', location: 'University of Exeter, Streatham Campus', lat: 50.737, long: -3.5351, artist: 'Luke Shepherd', owner: 'University of Exeter', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'campus', notes: '' },
  { name: 'Margaret Beckett', type: 'woman', location: 'University of Derby, Kedleston Rd', lat: 52.9378, long: -1.4903, artist: 'Shenda Amery', owner: 'University of Derby', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'campus', notes: '' },
  { name: 'Aphra Behn', type: 'woman', location: 'The Beaney, Canterbury', lat: 51.2794, long: 1.0778, artist: 'Christine Charlesworth', owner: 'Canterbury', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'public', notes: '' },
  { name: 'Dr Erinma Bell', type: 'woman', location: 'Manchester Town Hall', lat: 53.4794, long: -2.2449, artist: 'Karen Lyons', owner: 'Manchester City Council', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'public', notes: '' },
  { name: 'Jean Armour (Mauchline)', type: 'woman', location: 'Mauchline, East Ayrshire', lat: 55.5167, long: -4.3833, artist: 'Ruaraig McIver', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2002', form: 'statue', access: 'public', notes: '' },
  { name: 'Jean Armour (Dumfries)', type: 'woman', location: "Opposite St Michael's Church, Dumfries", lat: 55.069, long: -3.608, artist: 'Nautilus Burleighfield', owner: 'Burns Howff Club', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2004', form: 'statue', access: 'public', notes: 'approx town pin' },
  { name: 'Dame Louisa Aldrich-Blake', type: 'woman', location: 'Tavistock Square, Bloomsbury, London', lat: 51.5247, long: -0.1304, artist: 'Arthur George Walker', owner: 'Camden', source: 'PSSA', url: 'https://pssauk.org/women/', year: '1926', form: 'statue', access: 'public', notes: '' },
  { name: 'Catherine Booth', type: 'woman', location: 'Mile End Road, London', lat: 51.5242, long: -0.0334, artist: 'George Edward Wade', owner: 'Various', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'public', notes: '' },
  { name: 'Noor Inayat Khan', type: 'woman', location: 'Gordon Square Gardens, Bloomsbury, London', lat: 51.5236, long: -0.1309, artist: 'Karen Newman', owner: 'Camden / trust', source: 'PSSA', url: 'https://en.wikipedia.org/wiki/Noor_Inayat_Khan', year: '2012', form: 'bust', access: 'public', notes: '' },
  { name: 'Amy Johnson (Herne Bay)', type: 'woman', location: 'Herne Bay, Kent', lat: 51.3731, long: 1.1285, artist: 'Steven Melton', owner: 'Local', source: 'Art UK', url: 'https://en.wikipedia.org/wiki/Amy_Johnson', year: '', form: 'statue', access: 'public', notes: '' },
  { name: 'Amy Johnson (Hull)', type: 'woman', location: 'Prospect Street, Hull', lat: 53.7446, long: -0.3352, artist: 'Harry Ibbetson', owner: 'Local', source: 'Art UK', url: 'https://en.wikipedia.org/wiki/Amy_Johnson', year: '', form: 'statue', access: 'public', notes: '' },
  { name: 'Boudicca and Her Daughters', type: 'woman', location: 'Westminster Bridge, London', lat: 51.5009, long: -0.1217, artist: 'Thomas Thornycroft', owner: 'GLA', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Boadicea_and_Her_Daughters', year: '1902', form: 'group', access: 'public', notes: 'allegory_or_royal; not PSSA named-non-royal' },
  { name: 'Sarah Siddons', type: 'woman', location: 'Paddington Green, London', lat: 51.5194, long: -0.1757, artist: 'Léon-Joseph Chavalliaud', owner: 'Westminster', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Sarah_Siddons', year: '1897', form: 'statue', access: 'public', notes: '' },
  { name: 'Amy Winehouse', type: 'woman', location: 'Camden Market, London', lat: 51.5415, long: -0.1457, artist: 'Scott Eaton', owner: 'Camden', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Amy_Winehouse', year: '2014', form: 'statue', access: 'public', notes: '' },
  { name: 'Virginia Woolf', type: 'woman', location: 'Tavistock Square, Bloomsbury, London', lat: 51.5247, long: -0.1304, artist: 'Stephen Tomlin / bronze after', owner: 'Camden', source: 'PSSA', url: 'https://en.wikipedia.org/wiki/Statue_of_Virginia_Woolf', year: '2004', form: 'bust', access: 'public', notes: '' },
  { name: 'Ribbons (Leeds)', type: 'woman_collective', location: 'Playhouse Gardens, Leeds', lat: 53.8008, long: -1.5491, artist: 'Pippa Hale', owner: 'Leeds City Council', source: 'PSSA', url: 'https://ribbons-sculpture-leeds.co.uk/', year: '2022', form: 'group', access: 'public', notes: 'collective named women' },
  { name: 'Mary Barbour', type: 'woman', location: 'Govan Cross, Glasgow', lat: 55.8625, long: -4.3144, artist: 'Andrew Brown', owner: 'Glasgow City Council', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2018', form: 'statue', access: 'public', notes: '' },

  // —— Expansion: well-known missing women ——
  { name: 'Florence Nightingale', type: 'woman', location: 'Waterloo Place, London', lat: 51.50731, long: -0.13263, artist: 'Arthur George Walker', owner: 'English Heritage / Westminster', source: 'English Heritage', url: 'https://en.wikipedia.org/wiki/Statue_of_Florence_Nightingale,_London', year: '1915', form: 'statue', access: 'public', notes: '' },
  { name: 'Edith Cavell', type: 'woman', location: "St Martin's Place, London", lat: 51.509324, long: -0.127183, artist: 'George Frampton', owner: 'Westminster', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Edith_Cavell_Memorial', year: '1920', form: 'statue', access: 'public', notes: '' },
  { name: 'Mary Wollstonecraft', type: 'woman', location: 'Newington Green, London', lat: 51.5525, long: -0.0855, artist: 'Maggi Hambling', owner: 'Hackney / Mary on the Green', source: 'Art UK', url: 'https://artuk.org/discover/artworks/a-sculpture-for-mary-wollstonecraft-309902', year: '2020', form: 'statue', access: 'public', notes: 'figurative form controversial' },
  { name: 'Betty Campbell', type: 'woman', location: 'Central Square, Cardiff', lat: 51.478, long: -3.179, artist: 'Eve Shepherd', owner: 'Cardiff', source: 'Art UK', url: 'https://en.wikipedia.org/wiki/Betty_Campbell', year: '2021', form: 'statue', access: 'public', notes: 'approx square pin' },
  { name: 'George Eliot', type: 'woman', location: 'Newdegate Square, Nuneaton', lat: 52.523, long: -1.468, artist: 'John Letts', owner: 'Nuneaton', source: 'PSSA', url: 'https://pssauk.org/women/', year: '1986', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Alice Hawkins', type: 'woman', location: 'Market Place, Leicester', lat: 52.634, long: -1.133, artist: 'Sean Hedges-Quinn', owner: 'Leicester', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Alice_Hawkins', year: '2018', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Henrietta Lacks', type: 'woman', location: 'University of Bristol, Bristol', lat: 51.458, long: -2.602, artist: 'Helen Wilson-Roe', owner: 'University of Bristol', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Henrietta_Lacks', year: '2021', form: 'statue', access: 'campus', notes: 'approx' },
  { name: 'Margaret Thatcher (Grantham)', type: 'woman', location: 'St Peter’s Hill, Grantham', lat: 52.911, long: -0.641, artist: 'Douglas Jennings', owner: 'Local', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Margaret_Thatcher_(Grantham)', year: '2022', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Eleanor Rigby', type: 'woman', location: 'Stanley Street, Liverpool', lat: 53.406, long: -2.987, artist: 'Tommy Steele', owner: 'Liverpool', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Eleanor_Rigby_(statue)', year: '1982', form: 'statue', access: 'public', notes: 'fictional character; named woman figure' },
  { name: 'Ada Lovelace', type: 'woman', location: '7–9 Millbank / Horseferry Road, London', lat: 51.495, long: -0.126, artist: 'Dallas-Pierce-Quintero / others', owner: 'Private building', source: 'Art UK', url: 'https://artuk.org/discover/artworks/ada-lovelace-18151852-330833', year: '2022', form: 'statue', access: 'rooftop', notes: 'visible from street; rooftop siting' },
  { name: 'Joy Battick (Platform Piece)', type: 'woman', location: 'Brixton Station, London', lat: 51.463, long: -0.114, artist: 'Kevin Atherton', owner: 'Network Rail / Brixton', source: 'WomenstatuesUK', url: 'https://womenstatuesuk.com/', year: '1986', form: 'statue', access: 'public', notes: 'approx station pin; first named woman of colour statue in London' },
  { name: 'Black Mary (Mary Woolaston)', type: 'woman', location: "Calthorpe Community Garden, London", lat: 51.527, long: -0.116, artist: 'Marcia Bennett Male', owner: 'Community garden', source: 'WomenstatuesUK', url: 'https://womenstatuesuk.com/', year: '', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Elizabeth Fry', type: 'woman', location: 'Old Bailey, London', lat: 51.5155, long: -0.1015, artist: 'Alfred Drury / others', owner: 'City of London', source: 'WomenstatuesUK', url: 'https://womenstatuesuk.com/', year: '', form: 'statue', access: 'indoor', notes: 'tours; indoor' },
  { name: 'Dorothy Peel', type: 'woman', location: 'River Drive, South Shields', lat: 54.997, long: -1.439, artist: 'Unknown', owner: 'South Tyneside', source: 'WomenstatuesUK', url: 'https://womenstatuesuk.com/', year: '1987', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Mary Ann Macham', type: 'woman', location: 'North Shields riverside', lat: 55.008, long: -1.444, artist: 'Unknown', owner: 'North Tyneside', source: 'WomenstatuesUK', url: 'https://womenstatuesuk.com/', year: '2023', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Winifred Carney', type: 'woman', location: 'Belfast City Hall grounds', lat: 54.596, long: -5.93, artist: 'Unknown', owner: 'Belfast City Council', source: 'WomenstatuesUK', url: 'https://womenstatuesuk.com/', year: '2024', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Mary Ann McCracken', type: 'woman', location: 'Belfast City Hall grounds', lat: 54.5964, long: -5.9295, artist: 'Unknown', owner: 'Belfast City Council', source: 'WomenstatuesUK', url: 'https://womenstatuesuk.com/', year: '2024', form: 'statue', access: 'public', notes: 'approx; jittered vs Carney' },
  { name: 'Katie Ashbridge', type: 'woman', location: 'Malvern College, Worcestershire', lat: 52.108, long: -2.326, artist: 'Laura Lian', owner: 'Malvern College', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2011', form: 'statue', access: 'campus', notes: 'approx' },
  { name: 'Alison Balsom', type: 'woman', location: 'Green Street / Melbourn Road, Royston', lat: 52.048, long: -0.024, artist: 'Sustrans Project', owner: 'Sustrans', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'silhouette', access: 'public', notes: 'approx' },
  { name: 'Dame Eleanor Allan', type: 'woman', location: 'College House, Northumberland Road, Newcastle', lat: 54.978, long: -1.608, artist: 'Unknown', owner: 'Dame Allan’s School', source: 'PSSA', url: 'https://pssauk.org/women/', year: '1882', form: 'statue', access: 'campus', notes: 'architectural niche; approx' },
  { name: 'Emmeline and Christabel Pankhurst Memorial', type: 'woman', location: 'Victoria Tower Gardens, London', lat: 51.4975, long: -0.125, artist: 'A. G. Walker', owner: 'Westminster', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Emmeline_and_Christabel_Pankhurst_Memorial', year: '1930', form: 'statue', access: 'public', notes: 'approx gardens pin' },
  { name: 'Gracie Fields', type: 'woman', location: 'Town Hall Square, Rochdale', lat: 53.617, long: -2.159, artist: 'Unknown', owner: 'Rochdale', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Victoria Wood', type: 'woman', location: 'Library Gardens, Bury', lat: 53.593, long: -2.297, artist: 'Graham Ibbeson', owner: 'Bury', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2019', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Agatha Christie (Covent Garden)', type: 'woman', location: "Great Newport Street / Cranbourn Street, London", lat: 51.5116, long: -0.1278, artist: 'Ben Twiston-Davies', owner: 'Westminster', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2012', form: 'bust', access: 'public', notes: 'memorial bust' },
  { name: 'Emily Davison', type: 'woman', location: 'Carlton Park / Morpeth area, Northumberland', lat: 55.167, long: -1.687, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: 'verify exact siting' },
  { name: 'Sister Dora', type: 'woman', location: 'Walsall town centre', lat: 52.586, long: -1.983, artist: "F. J. Williamson", owner: 'Walsall', source: 'PSSA', url: 'https://pssauk.org/women/', year: '1886', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Grace Darling', type: 'woman', location: 'Bamburgh, Northumberland', lat: 55.608, long: -1.717, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Elsie Inglis', type: 'woman', location: 'Edinburgh', lat: 55.953, long: -3.189, artist: 'Unknown', owner: 'Edinburgh', source: 'Wikipedia category', url: 'https://en.wikipedia.org/wiki/Elsie_Inglis', year: '', form: 'statue', access: 'approx', notes: 'verify exact memorial location' },
  { name: 'Elizabeth Andrews', type: 'woman', location: 'Wales (see source)', lat: 51.75, long: -3.38, artist: 'Unknown', owner: 'Local', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Elizabeth_Andrews', year: '', form: 'statue', access: 'approx', notes: 'verify town' },
  { name: 'Sophia Duleep Singh (commemorations vary)', type: 'woman', location: 'London (suffrage heritage)', lat: 51.501, long: -0.142, artist: 'Various', owner: 'Various', source: 'PSSA / heritage', url: 'https://en.wikipedia.org/wiki/Sophia_Duleep_Singh', year: '', form: 'bust', access: 'approx', notes: 'placeholder pin near Buckingham Palace area; refine' },
  { name: 'Sylvia Pankhurst (Sustrans silhouette)', type: 'woman', location: 'London / Sustrans sites', lat: 51.527, long: -0.055, artist: 'Sustrans', owner: 'Sustrans', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'silhouette', access: 'approx', notes: 'one of multiple Sustrans silhouettes' },
  { name: 'Florence Nightingale (Aldershot bust)', type: 'woman', location: 'Aldershot', lat: 51.248, long: -0.767, artist: 'Amy Goodman', owner: 'Local', source: 'Art UK', url: 'https://artuk.org/discover/stories/redressing-the-balance-public-sculptures-of-women', year: '2021', form: 'bust', access: 'public', notes: 'approx' },
  { name: 'Margaret Thatcher (Guildhall Art Gallery)', type: 'woman', location: 'Guildhall, London', lat: 51.5158, long: -0.092, artist: 'Neil Simmons / others', owner: 'City of London', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Margaret_Thatcher_(London_Guildhall)', year: '1998', form: 'statue', access: 'indoor', notes: '' },
  { name: 'Diana Fountain (Green Park)', type: 'woman', location: 'Green Park, London', lat: 51.5045, long: -0.144, artist: 'Unknown', owner: 'Royal Parks', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Diana_Fountain,_Green_Park', year: '', form: 'statue', access: 'public', notes: 'allegorical Diana; not PSSA named-non-royal' },
  { name: 'A Surge of Power (Jen Reid)', type: 'woman', location: 'The Centre, Bristol (temporary history)', lat: 51.4545, long: -2.597, artist: 'Marc Quinn', owner: 'Temporary / documented', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/A_Surge_of_Power_(Jen_Reid)_2020', year: '2020', form: 'statue', access: 'approx', notes: 'removed; retained as historical record of public sculpture of a named woman' },
  { name: 'Messenger (Plymouth)', type: 'woman', location: 'Theatre Royal Plymouth', lat: 50.370, long: -4.143, artist: 'Joseph Hillier', owner: 'Plymouth', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Messenger_(sculpture_in_Plymouth)', year: '2019', form: 'statue', access: 'public', notes: 'female figure; confirm naming' },
  { name: 'The Ballad of Sophia Constable', type: 'woman', location: 'England (see Wikipedia)', lat: 51.28, long: 0.52, artist: 'Unknown', owner: 'Local', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/The_Ballad_of_Sophia_Constable', year: '', form: 'statue', access: 'approx', notes: 'verify location' },
  { name: 'Ethel Preston memorial', type: 'woman', location: 'England (see Wikipedia)', lat: 52.48, long: -1.89, artist: 'Unknown', owner: 'Local', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Ethel_Preston_memorial', year: '', form: 'statue', access: 'approx', notes: 'verify location' },
  { name: 'Queen Anne (Minehead)', type: 'woman', location: 'Minehead, Somerset', lat: 51.205, long: -3.478, artist: 'Unknown', owner: 'Local', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Queen_Anne,_Minehead', year: '', form: 'statue', access: 'public', notes: 'royal; not PSSA named-non-royal' },
  { name: 'Queen Anne (St Paul’s Churchyard)', type: 'woman', location: "St Paul's Churchyard, London", lat: 51.5136, long: -0.0985, artist: 'Francis Bird', owner: 'City of London', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Queen_Anne,_St_Paul%27s_Churchyard', year: '1712', form: 'statue', access: 'public', notes: 'royal' },
  { name: 'Queen Victoria (Bristol)', type: 'woman', location: 'College Green, Bristol', lat: 51.452, long: -2.601, artist: 'Joseph Edgar Boehm', owner: 'Bristol', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Queen_Victoria,_Bristol', year: '1888', form: 'statue', access: 'public', notes: 'royal' },
  { name: 'Queen Victoria (Brighton)', type: 'woman', location: 'Brighton', lat: 50.8225, long: -0.1372, artist: 'Unknown', owner: 'Brighton', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Queen_Victoria,_Brighton', year: '', form: 'statue', access: 'public', notes: 'royal; approx' },
  { name: 'Queen Victoria (Reading)', type: 'woman', location: 'Town Hall / Forbury area, Reading', lat: 51.455, long: -0.969, artist: 'George Blackall Simonds', owner: 'Reading', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Queen_Victoria,_Reading', year: '', form: 'statue', access: 'public', notes: 'royal; approx' },
  { name: 'Queen Victoria (Chester)', type: 'woman', location: 'Chester Castle / Grosvenor area', lat: 53.189, long: -2.892, artist: 'Unknown', owner: 'Chester', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Queen_Victoria,_Chester', year: '', form: 'statue', access: 'public', notes: 'royal; approx' },
  { name: 'Queen Victoria (St Helens)', type: 'woman', location: 'St Helens', lat: 53.454, long: -2.736, artist: 'Unknown', owner: 'St Helens', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Queen_Victoria,_St_Helens', year: '', form: 'statue', access: 'public', notes: 'royal; approx' },
  { name: 'Queen Victoria memorial (Leeds)', type: 'woman', location: 'Leeds', lat: 53.8008, long: -1.5491, artist: 'Unknown', owner: 'Leeds', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Memorial_to_Queen_Victoria,_Leeds', year: '', form: 'statue', access: 'public', notes: 'royal; approx' },
  { name: 'Elizabeth II (Oakham)', type: 'woman', location: 'Oakham, Rutland', lat: 52.671, long: -0.733, artist: 'Unknown', owner: 'Local', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Elizabeth_II,_Oakham', year: '', form: 'statue', access: 'public', notes: 'royal; approx' },
  { name: 'Elizabeth II (York Minster)', type: 'woman', location: 'York Minster, York', lat: 53.962, long: -1.082, artist: 'Unknown', owner: 'York Minster', source: 'Wikipedia', url: 'https://en.wikipedia.org/wiki/Statue_of_Elizabeth_II,_York_Minster', year: '', form: 'statue', access: 'public', notes: 'royal; approx' },
  { name: 'Sylvia Townsend Warner', type: 'woman', location: 'High Street, Dorchester', lat: 50.715, long: -2.437, artist: 'Unknown', owner: 'Dorchester', source: 'WomenstatuesUK', url: 'https://womenstatuesuk.com/', year: '2025', form: 'bench', access: 'public', notes: 'approx; statue-bench' },
  { name: 'Doreen (evacuee)', type: 'woman', location: 'Donyatt Halt, near Ilminster, Somerset', lat: 50.926, long: -2.941, artist: 'Ian Edwards', owner: 'Station project', source: 'WomenstatuesUK', url: 'https://womenstatuesuk.com/', year: '2009', form: 'statue', access: 'public', notes: 'approx' },
  { name: 'Geraldine Connor', type: 'woman', location: 'Leeds School of Arts, Portland Way, Leeds', lat: 53.802, long: -1.548, artist: 'Lara Rose', owner: 'Leeds Beckett / arts', source: 'WomenstatuesUK', url: 'https://womenstatuesuk.com/', year: '', form: 'statue', access: 'campus', notes: '3D-printed; indoor foyer possible' },

  // More PSSA / campaign names with town pins (expand coverage; refine later)
  { name: 'Enid Blyton', type: 'woman', location: 'Broadstairs / Isle of Thanet area', lat: 51.359, long: 1.439, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: '' },
  { name: 'Margot Fonteyn', type: 'woman', location: 'UK (see PSSA)', lat: 51.5, long: -0.12, artist: 'Unknown', owner: 'Various', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'refine location' },
  { name: 'Marie Curie memorials (UK sites)', type: 'woman', location: 'Multiple UK sites — London pin', lat: 51.515, long: -0.145, artist: 'Various', owner: 'Various', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'representative pin; split rows later' },
  { name: 'Octavia Hill', type: 'woman', location: 'UK (see PSSA)', lat: 51.494, long: -0.135, artist: 'Unknown', owner: 'Various', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'refine' },
  { name: 'Elizabeth Garrett Anderson', type: 'woman', location: 'London / Aldeburgh area — London pin', lat: 51.524, long: -0.135, artist: 'Unknown', owner: 'Various', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'refine' },
  { name: 'Rosalind Franklin', type: 'woman', location: 'UK campuses / London', lat: 51.523, long: -0.128, artist: 'Various', owner: 'Various', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'refine' },
  { name: 'Dorothy Hodgkin', type: 'woman', location: 'Oxford area', lat: 51.752, long: -1.258, artist: 'Various', owner: 'Oxford', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'refine' },
  { name: 'Barbara Castle', type: 'woman', location: 'Blackburn / UK', lat: 53.748, long: -2.482, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: '' },
  { name: 'Barbara Hepworth commemorations', type: 'woman', location: 'Wakefield / St Ives — Wakefield pin', lat: 53.683, long: -1.498, artist: 'Various', owner: 'Various', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: 'artist commemorations; refine' },
  { name: 'Mary Kingsley', type: 'woman', location: 'UK (see PSSA)', lat: 51.48, long: -3.18, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'refine' },
  { name: 'Mary Quant', type: 'woman', location: 'London', lat: 51.512, long: -0.138, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: 'refine' },
  { name: 'Vivien Leigh', type: 'woman', location: 'UK (see PSSA)', lat: 51.51, long: -0.13, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'refine' },
  { name: 'Glenda Jackson memorials', type: 'woman', location: 'UK (see PSSA)', lat: 51.55, long: -0.14, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'refine' },
  { name: 'Helen Sharman', type: 'woman', location: 'Sheffield area', lat: 53.381, long: -1.47, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: '' },
  { name: 'Tanni Grey-Thompson', type: 'woman', location: 'UK (see PSSA)', lat: 51.48, long: -3.18, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: 'refine' },
  { name: 'Nicola Adams', type: 'woman', location: 'Leeds area', lat: 53.8, long: -1.55, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: 'refine' },
  { name: 'Kelly Holmes', type: 'woman', location: 'Kent / UK', lat: 51.27, long: 0.52, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: 'refine' },
  { name: 'Mary Peters', type: 'woman', location: 'Belfast area', lat: 54.6, long: -5.93, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: '' },
  { name: 'Hylda Baker', type: 'woman', location: 'Farnworth / Bolton area', lat: 53.55, long: -2.4, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: '' },
  { name: 'Thora Hird', type: 'woman', location: 'Morecambe / Lancashire', lat: 54.07, long: -2.86, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: '' },
  { name: 'Bessie Braddock', type: 'woman', location: 'Lime Street Station, Liverpool', lat: 53.408, long: -2.978, artist: 'Tom Murphy', owner: 'Liverpool', source: 'PSSA', url: 'https://pssauk.org/women/', year: '2009', form: 'statue', access: 'public', notes: 'approx station pin' },
  { name: 'Annie Kenney', type: 'woman', location: 'Oldham / Greater Manchester', lat: 53.54, long: -2.11, artist: 'Unknown', owner: 'Local', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'statue', access: 'approx', notes: '' },
  { name: 'Christabel Pankhurst (various)', type: 'woman', location: 'UK (see PSSA) — London pin', lat: 51.498, long: -0.124, artist: 'Various', owner: 'Various', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'in addition to Victoria Tower Gardens memorial' },
  { name: 'Mary Seacole (other UK commemorations)', type: 'woman', location: 'UK (see PSSA) — secondary pin', lat: 51.499, long: -0.119, artist: 'Various', owner: 'Various', source: 'PSSA', url: 'https://pssauk.org/women/', year: '', form: 'bust', access: 'approx', notes: 'secondary commemorations beyond St Thomas Hospital; refine or merge' },

  // —— Goats (broad) ——
  { name: 'I Goat (Kenny Hunter)', type: 'goat', location: 'Brushfield Street, Spitalfields, London', lat: 51.5194, long: -0.075, artist: 'Kenny Hunter', owner: 'Spitalfields', source: 'Art UK', url: 'https://artuk.org/discover/artworks/i-goat-312187', year: '2010', form: 'statue', access: 'public', notes: '' },
  { name: 'Kashmir Goat (Great Orme)', type: 'goat', location: 'Great Orme Visitor Centre, Llandudno', lat: 53.3289, long: -3.8286, artist: 'Graham High', owner: 'Local authority', source: 'Art UK', url: 'https://artuk.org/discover/artworks/kashmir-goat-307640', year: '', form: 'statue', access: 'public', notes: '' },
  { name: 'Goats (Sally Matthews series)', type: 'goat', location: 'Gateshead Riverside Park', lat: 54.9637, long: -1.6126, artist: 'Sally Matthews', owner: 'Gateshead Council', source: 'Gateshead Council', url: 'https://www.gateshead.gov.uk/article/4588/Goats', year: '1992', form: 'group', access: 'public', notes: 'seven life-sized goats' },
  { name: 'Redesdale Goat (Carter Bar)', type: 'goat', location: 'Carter Bar, Northumberland/Scotland border', lat: 55.3667, long: -2.3333, artist: 'Stephen Lunn', owner: 'NNPA / local', source: 'Art UK', url: 'https://artuk.org/discover/artworks/redesdale-goat-337395', year: '', form: 'statue', access: 'public', notes: '' },
  { name: 'Nibbling Goat (Georg Ehrlich)', type: 'goat', location: 'The Hepworth Wakefield', lat: 53.6789, long: -1.4917, artist: 'Georg Ehrlich', owner: 'Hepworth Wakefield', source: 'Art UK', url: 'https://artuk.org/discover/artworks/nibbling-goat-275633', year: '', form: 'statue', access: 'museum', notes: '' },
  { name: 'Johann', type: 'goat', location: 'Knocknacarry Road, Cushendun, Co. Antrim', lat: 55.125, long: -6.042, artist: 'Deborah Brown', owner: 'People of Cushendun', source: 'Art UK', url: 'https://artuk.org/discover/artworks/johann-322850', year: '2002', form: 'statue', access: 'public', notes: 'approx shore pin; foot-and-mouth memorial' },
  { name: 'Mountain Goat', type: 'goat', location: 'Edge Hill University, Ormskirk', lat: 53.56, long: -2.87, artist: 'Tony Evans', owner: 'Edge Hill University', source: 'Art UK', url: 'https://artuk.org/discover/artworks/mountain-goat-267724', year: '2010', form: 'statue', access: 'campus', notes: 'approx campus pin' },
  { name: "Goatherd's Daughter", type: 'goat_with_figure', location: "St John's Lodge Gardens, Regent's Park, London", lat: 51.5285, long: -0.152, artist: 'C. L. Hartwell', owner: 'Royal Parks', source: 'Bob Speel', url: 'http://www.speel.me.uk/gp/goats.htm', year: '', form: 'group', access: 'public', notes: 'woman with kid goat' },
  { name: 'Natural History Museum goat medallion', type: 'goat_relief', location: 'Natural History Museum, Cromwell Road, London', lat: 51.496, long: -0.176, artist: 'Architectural sculpture', owner: 'NHM', source: 'Bob Speel', url: 'http://www.speel.me.uk/gp/goats.htm', year: '', form: 'relief', access: 'public', notes: 'architectural roundel' },
  { name: 'Cardiff heraldic goat (lamp-holder)', type: 'goat_heraldic', location: 'Cardiff city centre', lat: 51.481, long: -3.179, artist: 'Unknown', owner: 'Cardiff', source: 'Bob Speel', url: 'http://www.speel.me.uk/gp/goats.htm', year: '', form: 'relief', access: 'public', notes: 'heraldic goat rampant; curated heraldic sample' },
  { name: 'Goat and kid (Victorian orangery group)', type: 'goat', location: 'UK collection (see Speel)', lat: 51.5, long: -0.15, artist: 'Unknown', owner: 'Various', source: 'Bob Speel', url: 'http://www.speel.me.uk/gp/goats.htm', year: '', form: 'group', access: 'approx', notes: 'curated Speel example; refine siting' },
]

export const CSV_COLUMNS = [
  'name',
  'type',
  'location',
  'lat',
  'long',
  'artist',
  'owner',
  'source',
  'url',
  'year',
  'form',
  'access',
  'notes',
] as const
